// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZw7mfemHfe7A0gv62rnzJMGw5xYLub_8',
    appId: '1:41538930903:web:0e28a8217027f8bf13c892',
    messagingSenderId: '41538930903',
    projectId: 'chatapp-c8d93',
    authDomain: 'chatapp-c8d93.firebaseapp.com',
    storageBucket: 'chatapp-c8d93.appspot.com',
    measurementId: 'G-CG5MWY5VG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaS_duSy4PkTt8IabFOlFUUgMRyDsiMRw',
    appId: '1:41538930903:android:4a0133b1133a3df813c892',
    messagingSenderId: '41538930903',
    projectId: 'chatapp-c8d93',
    storageBucket: 'chatapp-c8d93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_pt1OPscqdgAHIC1OojjPzaYcQwhBoQ',
    appId: '1:41538930903:ios:ee8bba6e4b71f00113c892',
    messagingSenderId: '41538930903',
    projectId: 'chatapp-c8d93',
    storageBucket: 'chatapp-c8d93.appspot.com',
    iosClientId: '41538930903-jtv2b5f07pmcv0pu8h05llt51tt3blsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR_pt1OPscqdgAHIC1OojjPzaYcQwhBoQ',
    appId: '1:41538930903:ios:ee8bba6e4b71f00113c892',
    messagingSenderId: '41538930903',
    projectId: 'chatapp-c8d93',
    storageBucket: 'chatapp-c8d93.appspot.com',
    iosClientId: '41538930903-jtv2b5f07pmcv0pu8h05llt51tt3blsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );
}
